drivers: power: supply/qcom: Remove unused var pval
../../../../../../kernel/xiaomi/sweet/drivers/power/supply/qcom/smb5-lib.c:1771:29: error: unused variable 'pval' [-Werror,-Wunused-variable]
        union power_supply_propval pval = {0, };
                                   ^
1 error generated.

Change-Id: Ie52d4b2d9914e307533466c81f2c316c1119a568